### ISSUE TITLE
Build problems

### ISSUE THREAD

**Issue by invidia0** [mayataka/unitree_ros2#5]
Hi, 

thank you very much for providing this repo! Great work!
Anyway i have an issue regarding the field names of the msgs you defined in the unitree_msgs package. Basically ROS2 says that he wants the field names declared in lower case without any upper case as you instead defined.

> "Field names must be lowercase alphanumeric characters with underscores for separating words. They must start with an alphabetic character, they must not end with an underscore and never have two consecutive underscores."
In [https://docs.ros.org/en/humble/Concepts/About-ROS-Interfaces.html#field-names](url)

> float64 t                          # Time 
float64[12] qJ                     # Joint position measurements
float64[12] vJ                    # Joint velocity measurements
float64[12] tauJ                   # Joint torque measurements
float64[4] imu_orientation         # Imu orientation estimation expressed as a quaternion (x, y, z, w)
float64[3] imu_angular_velocity    # Imu angular velocity
float64[3] imu_linear_acceleration # Imu linear acceleration 
float64[4] foot_force_sensor       # Force sensor measurements 

The problems are the "J" and rewriting the msg with them in lower case solves the problem but obviously it generates others in the unitree_hardware package.
So i am wondering how did you manage to build the package? I am building this package on **Foxy** but also Humble mentions this constraint on the field names.
![2022-09-26_22-21](https://user-images.githubusercontent.com/78743911/192372418-632ccd02-08c1-4817-b6eb-26d927b88571.png)

Thank you in advice!

**Comment by mayataka** [comment]
Hi @invidia0,

I consider only Humble, so there is no wonder if the build fails with Foxy.
There can be other problems other than the msgs with Foxy because there are many differences around ros2_control between Foxy and Humble.

**Comment by invidia0** [comment]
Hi @mayataka,

thank you for you response! I imagined that! However i just saw there's a foxy branch, does it make sense to consider it or is it better to switch to humble and take the last branch?
Thank you in advice!

**Comment by invidia0** [comment]
> Hi @invidia0,
> 
> I consider only Humble, so there is no wonder if the build fails with Foxy. There can be other problems other than the msgs with Foxy because there are many differences around ros2_control between Foxy and Humble.

**Comment by mayataka** [comment]
@invidia0 
Foxy branch is a deprecated branch. It is no longer maintained and it might not work.
